sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t daniel/react-dev .

script:
  - docker run -e CI=true daniel/react-dev npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: react-app
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-814971353988"
  bucket_path: "react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
